### ISSUE TITLE
Add full set of bracket sizes

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#117]
The following bracket characters have only four sizes and they are
much smaller than the sizes provided by STIX 1 fonts. In contrast
“()[]{}” have 12 sizes.

U+2985, U+2986, U+27E6, U+27E7, U+230A, U+230B, U+2308, U+2309,
U+2983, U+2984, U+27E8, U+27E9, U+27EA, U+27EB, U+2772, U+2773

**Comment by tiroj** [comment]
Logged to fix in 2.0.1

Plan is to adjust size of existing variants and to add additional sizes and also elements to build taller versions, matching behaviour for () [] {}. NB: will require update to MATH table.

**Comment by tiroj** [comment]
[✓ Tiro internal]

Note: glyph work completed, including revision of all existing delimeters for consistency of heights and spacing. MATH table work to be done.

**Comment by tiroj** [comment]
[✓ Tiro internal]

MATH table updated.

Note: four pairs of delimeters now have full set of 12 growing form variants, but do not have assemblies for extra-large forms, which could be added (consider for 2.1.0?); two other pairs now have full set of 12 growing forms but would not be candidates for assemblies due to their shape.
