### ISSUE TITLE
Support Unicode 11 Mathematical Standardized Variants

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#122]
See https://www.unicode.org/Public/11.0.0/ucd/StandardizedVariants.txt

**Comment by tiroj** [comment]
We have glyphs for some (most?) of these already, but they are not mapped to Variant Selector 1 (U+FE00) sequences. This is relatively easy to do, but means adding a format 14 cmap table to the fonts. This will make the sources a bit less friendly to editing if someone wants to fork the fonts, since a lot of font tools won't write format 14 cmap.

**Comment by tiroj** [comment]
Logged to add support in 2.0.1

**Comment by davidmjones** [comment]
These look good except for two things:

* The mapping for 0030 FE00 to zero.VS1 is missing from the format 14 cmap table.
* The default and variant versions of U+229C are swapped.
