### ISSUE TITLE
Inconsistency of bigger braces

### ISSUE THREAD

**Issue by zepinglee** [stipub/stixfonts#124]
A minimal piece of XeLaTeX code:
```TeX
\documentclass{article}
\usepackage{amsmath,unicode-math}
\setmathfont{STIX2Math.otf}
\begin{document}
\[ f(x) = \begin{cases} 0, \\ 1.       \end{cases} \]
\[ f(x) = \begin{cases} 0, \\ 1, \\ 2. \end{cases} \]
\end{document}
```

Output:
![screen shot 2018-07-26 at 9 45 12 pm](https://user-images.githubusercontent.com/12290822/43266154-37a98448-911d-11e8-9507-b049e2e4c2d2.png)

The former brace is so “curly” that it is inconsistent with the latter one. Is this an intensional design?

**Comment by davidmjones** [comment]
Probably not intentional.  This is closely related to #117.  I'll add it to be reviewed as part of the 2.0.1 milestone.

**Comment by tiroj** [comment]
The second, taller brace is composed of stacked elements, so needs to be straight. The first is an individual glyph, so can be more naturally formed, following a traditional curvature for this character. I agree that they look inconsistent when viewed together.

Q. Should the individual brace glyphs (various sizes) be made less curvy so that they coordinate visually with taller braces built from stacked elements?

**Comment by tiroj** [comment]
[✓ Tiro internal]
