### ISSUE TITLE
Bug in moustache (at least in Type1) and extensible delimiters in large symbol font have steps that are too large

### ISSUE THREAD

**Issue by FrankMittelbach** [stipub/stixfonts#134]
Consider the following input:

```
\documentclass{article}

\usepackage{stix2}

\begin{document}

\[
\left(
    \frac{\left\lmoustache\mathcal{Q}(t)\right\rmoustache}
         {\sqrt {1 - t^2}}
    \right)
\]


\setlength\delimitershortfall{-1pt}  % make delimiter grow

\[
\left\lbrace\left\lbrace\left\lbrace\left\lbrace \left\lbrace\left\lbrace
\left\lbrace\left\lbrace
     \mathcal{Q}
\right\rangle \right\rangle\right\rangle\right\rangle\right\rangle\right\rangle
\right\rangle\right\rangle
\]

\[
\left\lmoustache\left\lmoustache\left\lmoustache\left\lmoustache \left\lmoustache
     \mathcal{Q}
\right\rmoustache \right\rmoustache\right\rmoustache\right\rmoustache\right\rmoustache
\]

\end{document}
```
The result is:

<img width="270" alt="bildschirmfoto 2019-02-28 um 23 53 35" src="https://user-images.githubusercontent.com/1062981/53604217-24427d00-3bb4-11e9-8de0-887a12dc9b31.png">

This exhibits two problems:  (A) there is a gap in the moustache delimiters.
(B) The sizes are much too big (due to the extensible parts are made up from fairly large components. As a result the fraction looks awful.

In contrast the same file with std CM fonts:

<img width="294" alt="bildschirmfoto 2019-02-28 um 23 56 54" src="https://user-images.githubusercontent.com/1062981/53604384-94510300-3bb4-11e9-8050-f2c586f11886.png">

This has a much more reasonable set of sizes in the extensions (especially for the more common curly braces). Also note that stix2 seems to have (Type1) only 3 sizes in \rangle while CM offers 5 so that is also very limiting

**Comment by tiroj** [comment]
I think the examples shown here are pre-2.10 versions, yes?

In 2.10 we extended and revised the range of growing forms of delimiters so that most delimiters have 12 variant heights (after which assembles may be used). This should provide more granulation in the height variant selection:
![image](https://user-images.githubusercontent.com/5614500/125357260-3ef89500-e31c-11eb-9803-2cbb9eb62033.png)

In 2.20 we have spec’d to add the same set of height variants to remaining delimiters.

**Comment by FrankMittelbach** [comment]
I guess they are pre 2.10. However, if there are new version then these versions have never made it as Type-1 fonts into the standard TeX distributions. Looking at

https://www.ctan.org/pkg/stix2-type1

you see that what is distributed as of today is 2.0 and os that is what people get with a current system. I don't know who is responsible to make these available, the page suggests @davidmjones   I guess.

**Comment by davidmjones** [comment]
@FrankMittelbach As mentioned on the CTAN page, we are no longer actively supporting the Type 1 versions of the fonts.  Updating them takes too many resources that are better spent on improving the OpenType fonts.

I guess I didn't notice that this issue was about the Type 1 fonts.  I'm closing it here.  You could resubmit it to https://github.com/stipub/stix_type1 in case anyone in the community wants to volunteer some time to address it.
