### ISSUE TITLE
Monospace Capital Symbols are wider than Small Symbols

### ISSUE THREAD

**Issue by keithxemi** [stipub/stixfonts#154]
There is a difference of about 10% in the width of the 1d670-1d689 MATHEMATICAL MONOSPACE CAPITAL A-Z symbols compared to the 1d68a-1d6a3 MATHEMATICAL MONOSPACE SMALL a-z symbols. These should be the same width so they are monospaced.

**Comment by tiroj** [comment]
This was an intentional design decision for v2.10. We discussed this at some length internally, and with STI Pub stakeholders. Our reasoning is that ‘monospace’ in the context of math alphanumerics is a style, rather than a technically specific label. So what is essential is that these characters a) are visually distinct from other styles, and b) have the general appearance of the styles of serifed typewriter fonts from which they derive. I would have favoured Unicode calling them ‘typewriter’ characters rather than monospaced. Since part of the style of these letters does arise from the way in which narrow and wide letters were fitted to common widths for typewriter composition, we kept the monospaced nature of within each case, but didn’t want to make either the lowercase too wide or the uppercase too narrow.
