### ISSUE TITLE
U+2216 SET MINUS is too small?

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#179]
@pkra points out that U+2216 looks undersized.  I would expect it to be the same size as U+2215 DIVISION SLASH, but reversed.

The official Unicode charts display the same difference in size between the example glyphs for the two characters; I suspect the original STIX design was based on the Unicode chart and never revised.

**Comment by xsrvmy** [comment]
Would this be just a problem in word (just guessing because Cambria Math doesn't have \setminus)?
In LaTeX \setminus is mapped to the reverse solidus character, and \smallsetminus is mapped to 2216.

**Comment by pkra** [comment]
> Would this be just a problem in word (just guessing because Cambria Math doesn't have \setminus)?
> In LaTeX \setminus is mapped to the reverse solidus character, and \smallsetminus is mapped to 2216.

Neither. This came up in web content.

**Comment by tiroj** [comment]
Investigating this further: the Math font contains two different glyphs for U+2216. The default (encoded) form /uni2216/ is a small one, vertically centred on the math alignment midline. The other is a variant /uni2216.var/ which has the same proportions as the division slash /uni2215/, as requested by @pkra — I think this must be a legacy from somewhere earlier in the life of the STIX fonts: in Cambria, our U+2216 glyph is large.

/uni2216.var/ is accessible via the Stylistic Set 14 (ss14) layout feature.

Note that the new ssty and ssty2 sets include scaling optical size variants for U+2216, but only for the current default, small form, not for the larger variant.

@davidmjones How should I proceed? I am wary about swapping the default and variant forms because that would reverse the display of any documents already using ss14 to access the larger form. I am thinking, though, that I should probably add ssty and ssty2 variants of the larger form.

**Comment by tiroj** [comment]
To confirm: if we revise as you suggest, we would simply swap the two glyphs, so /uni2216/ becomes the larger form, and /uni2216.var/ becomes the smaller form, with the latter still mapped in the ss14 stylistic feature. I don’t think there are any knock-on dependencies in the font data, but would check kerning and MATH table to make sure.

**Comment by doylemd** [comment]
I agree with this general approach and the need to make this more consistent with expectations set by other fonts. I am wondering, though, whether these changes along with the changing width of the binary operators are sufficiently "different" from past versions of the font to warrant tagging these changes as 2.2 instead of 2.12 and then perhaps moving our planning for 2.2 to be about 2.3.

**Comment by tiroj** [comment]
I generally treat revisions to existing glyphs as minor-minor, and reserve minor revision updates for significant extensions of capability involving e.g. lots of new glyphs or changes of behaviour affecting large portions of the font. But up to STI Pub in this case.

**Comment by tiroj** [comment]
On the subject of versioning: If we exhaust minor version revisions for 2.xx, do we have STIX Two v3.xx, or do we have STIX Three? :)

**Comment by davidmjones** [comment]
> To confirm: if we revise as you suggest, we would simply swap the two glyphs, so /uni2216/ becomes the larger form, and /uni2216.var/ becomes the smaller form, 

Yes to this.

> with the latter still mapped in the ss14 stylistic feature

I think it would be better to remove it from ss14 and put it in cv04.

BTW, I'm kind of confused about the other two mappings in ss14, but I don't want to think about them if I don't have to.

**Comment by davidmjones** [comment]
> On the subject of versioning: If we exhaust minor version revisions for 2.xx, do we have STIX Two v3.xx, or do we have STIX Three? :)

Don't make me come over there. :)

**Comment by xsrvmy** [comment]
Interesting issue about the unicode-math fonts situation: The \smallsetminus character in LM is still smaller than the regular set minus operator from regular latex. The latex setminus is just a backslash, so \mathbin{\backslash}

**Comment by tiroj** [comment]
Fixed for v2.12:

a) Swapped glyphs and spacing for /uni2216/ and /uni2216.var/

b) Replaced /uni2216.ssty/ and /uni2216.ssty2/ with scaling optical versions of the new, larger U+2216 default form.

c) Added /uni2216.var.ssty/ and /uni2216.var.ssty2/ glyphs, and moved the existing smaller form versions to these locations.

d) Updated OpenType Layout project as follows:

- added new var.ssty glyphs and mapped in ssty layout GSUB code
- removed mapping of /uni2216/ to /uni2216.var/ from ss14 GSUB code
- added new cv04 feature to GSUB code and mapped /uni2216/ to /uni2216.var/
- reordered cv and ss15 lookups to before ssty lookups to ensure access to scaling variant output
