### ISSUE TITLE
Adobe Acrobat will not use same spacing for STIX 2.0 text font as Word

### ISSUE THREAD

**Issue by davidmjones** [stipub/stixfonts#89]
I created a lot of MS Word files with desired pagination using 2.0 STIX text font. Adobe Acrobat XI will not display the Word Files with the correct spacing or pagination. STIX 1.0 works fine (but can't be substituted because the spacing is different). Will this be fixed?

Reported by: jnperdue

Original Ticket: [stixfonts/tracking/89](https://sourceforge.net/p/stixfonts/tracking/89)

**Comment by tiroj** [comment]
Most fonts have different vertical metrics settings, resulting in incompatible linespacing when these metrics are relied upon instead of explicit linespacing values (leading). If matching the STIX 1.0 metrics had been identified as a technical requirement, we could have done that, but I consider it too late now to change, since to do so would cause breaking reflow of documents made with STIX Two.
